#ifndef CONFIG_H
#define CONFIG_H

// --- CONFIGURAÇÕES DA REDE SEM FIO  ---
#define WLAN_SSID "SUA_REDE_SEM_FIO"
#define WLAN_PASS "SENHA_DA_REDE"

// --- HOSTNAME DO DISPOSITIVO ---
#define HOSTNAME "NOME_DO_GRUPO"
#endif
